// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: honks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createHonk = `-- name: CreateHonk :one
INSERT INTO honks (id, created_at, updated_at, body, post_id, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, body, post_id, user_id
`

type CreateHonkParams struct {
	Body   string
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateHonk(ctx context.Context, arg CreateHonkParams) (Honk, error) {
	row := q.db.QueryRowContext(ctx, createHonk, arg.Body, arg.PostID, arg.UserID)
	var i Honk
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.PostID,
		&i.UserID,
	)
	return i, err
}
