// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kreeyaws.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createKreeyaw = `-- name: CreateKreeyaw :one
INSERT INTO kreeyaws (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateKreeyawParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateKreeyaw(ctx context.Context, arg CreateKreeyawParams) (Kreeyaw, error) {
	row := q.db.QueryRowContext(ctx, createKreeyaw, arg.Body, arg.UserID)
	var i Kreeyaw
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteAllKreeyaws = `-- name: DeleteAllKreeyaws :exec
DELETE FROM kreeyaws
`

func (q *Queries) DeleteAllKreeyaws(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllKreeyaws)
	return err
}

const deleteKreeyaw = `-- name: DeleteKreeyaw :exec
DELETE FROM kreeyaws
WHERE id = $1
`

func (q *Queries) DeleteKreeyaw(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKreeyaw, id)
	return err
}

const getKreeyaw = `-- name: GetKreeyaw :one
SELECT id, created_at, updated_at, body, user_id FROM kreeyaws
WHERE id = $1
`

func (q *Queries) GetKreeyaw(ctx context.Context, id uuid.UUID) (Kreeyaw, error) {
	row := q.db.QueryRowContext(ctx, getKreeyaw, id)
	var i Kreeyaw
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getKreeyawsByAuthor = `-- name: GetKreeyawsByAuthor :many
SELECT id, created_at, updated_at, body, user_id FROM kreeyaws
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetKreeyawsByAuthor(ctx context.Context, userID uuid.UUID) ([]Kreeyaw, error) {
	rows, err := q.db.QueryContext(ctx, getKreeyawsByAuthor, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kreeyaw
	for rows.Next() {
		var i Kreeyaw
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKreeyawsCreatedAtAsc = `-- name: GetKreeyawsCreatedAtAsc :many
SELECT id, created_at, updated_at, body, user_id FROM kreeyaws
ORDER BY created_at
`

func (q *Queries) GetKreeyawsCreatedAtAsc(ctx context.Context) ([]Kreeyaw, error) {
	rows, err := q.db.QueryContext(ctx, getKreeyawsCreatedAtAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kreeyaw
	for rows.Next() {
		var i Kreeyaw
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
