// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kreeyaws.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createKreeyaw = `-- name: CreateKreeyaw :one
INSERT INTO kreeyaws (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateKreeyawParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateKreeyaw(ctx context.Context, arg CreateKreeyawParams) (Kreeyaw, error) {
	row := q.db.QueryRowContext(ctx, createKreeyaw, arg.Body, arg.UserID)
	var i Kreeyaw
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
